### ISSUE TITLE
bug in queries.js

### ISSUE THREAD

**Issue by cmaixen** [PubDig/pubdig#13]
```ReferenceError: Invalid left-hand side in assignment
    at Object.<anonymous> (/Users/yannickmerckx/Documents/Development/pubdig/lib/queries.js:101:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/yannickmerckx/Documents/Development/pubdig/backend/user.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)```

**Comment by cmaixen** [comment]
This bug is probably introduced by #12
