### ISSUE TITLE
Api /users not stable.

### ISSUE THREAD

**Issue by cmaixen** [PubDig/pubdig#2]
You get weird errors when making calls via the api `/users` . For example:
When you try to get a respons via curl as `curl -H "Content-type:application/json" http://127.0.0.1:3000/api/v1/users`. You get a 400 and on the backend you get the following error: 
    
    SELECT user_id FROM `%prefix%users`
    error: [TypeError: Object #<RowDataPacket> has no method 'map']
    TypeError: Object #<RowDataPacket> has no method 'map'
    at /Users/yannickmerckx/Documents/Development/pubdig/backend/user.js:13:29
    at tryCatchReject (/Users/yannickmerckx/Documents/Development/pubdig/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/yannickmerckx/Documents/Development/pubdig/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/yannickmerckx/Documents/Development/pubdig/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/yannickmerckx/Documents/Development/pubdig/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/yannickmerckx/Documents/Development/pubdig/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/yannickmerckx/Documents/Development/pubdig/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:419:13)
```

**Comment by cmaixen** [comment]
Resolved by #3 .
